server:
  port: 8080
spring:
  security:
    user:
      name: mani
      password: manipass
      roles: ADMIN,USER
security:
  oauth2:
    client:
      client-id: testclient
      client-secret: testpass
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      scope: READ,WRITE
